project:
  type: website
  pre-render:
    - python scripts/openalex_to_yaml.py
    - sass styles/custom.scss:_site/styles/custom.css

jupyter:
  kernel: quarto-env

website:
  title: "Machine Learning for Materials Design<br>(Cangi Lab)"
  site-url: "https://www.ml4md.de"
  description: "Official website of the Machine Learning for Materials Design (ML4MD) Lab, led by Attila Cangi. Research focuses on artificial intelligence, machine learning, neural networks, electronic structure, density functional theory and atomistic simulations for materials science."
  page-navigation: true
  open-graph: true                          # social cards
  search: true
  navbar:
    left:
      #- href: index.qmd
      #  text: Home
      - href: news.qmd
        text: News
        icon: chat-left-text                # Icons from https://icons.getbootstrap.com/
      - text: Research
        href: research/index.qmd
        icon: rocket-takeoff
        #menu:
        #  - href: research/index.qmd
        #    text: Overview
        #  - href: research/highlights.qmd
        #    text: Research Highlights
      - href: people.qmd
        text: People
        icon: people-fill
      - href: publications.qmd
        text: Publications
        icon: book
      - href: teaching.qmd
        text: Teaching
        icon: mortarboard
      - href: contact.qmd
        text: Contact
        icon: envelope
      - href: https://codebase.helmholtz.cloud/casus/mlmd/info
        text: Internal
        icon: bi-box-arrow-in-down-left
  page-footer:
    center: "© 2025 [Attila Cangi](https://www.hzdr.de/db/!ContMan.Visi.Card?pUser=139621&pNid=1227&pLang=en) · [Impressum](/disclaimer.qmd) · Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: cosmo
    css: /styles/custom.css
    toc: false
    include-in-header: _includes/head_meta.html

markdown_extensions:
  - attr_list
