---
title: "Contact"
---

[Attila Cangi](https://www.hzdr.de/db/!ContMan.Visi.Card?pUser=139621&pNid=1227&pLang=en){target="_blank"}<br>
[Department Machine Learning for Materials Design](https://www.casus.science/?page_id=4660){target="_blank"}<br>
[Center for Advanced Systems Understanding (CASUS)](https://www.casus.science){target="_blank"}<br> 
[Helmholtz‑Zentrum Dresden‑Rossendorf (HZDR)](https://www.hzdr.de){target="_blank"}<br>

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2502.4633107893223!2d14.974382076604273!3d51.15524733636819!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4708dd50d7252c41%3A0x2b8364884b1f8926!2sCASUS%20-%20Center%20for%20Advanced%20Systems%20Understanding%20am%20HZDR!5e0!3m2!1sen!2sde!4v1751294459296!5m2!1sen!2sde" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>



### Legal Disclaimer
Last updated: July 1, 2025

#### Interpretation and Definitions
##### Interpretation
The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

##### Definitions
For the purposes of this Disclaimer:
Company (referred to as either "the Company", "We", "Us" or "Our" in this Disclaimer) refers to Machine Learning for Materials Design.
Service refers to the Website.
You means the individual accessing the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
Website refers to Machine Learning for Materials Design, accessible from https://acangi.github.io/ml4md.

##### Disclaimer
The information contained on the Service is for general information purposes only.
The Company assumes no responsibility for errors or omissions in the contents of the Service.
In no event shall the Company be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice. This Disclaimer has been created with the help of the Disclaimer Generator.
The Company does not warrant that the Service is free of viruses or other harmful components.

##### External Links Disclaimer
The Service may contain links to external websites that are not provided or maintained by or in any way affiliated with the Company.
Please note that the Company does not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.

##### Errors and Omissions Disclaimer
The information given by the Service is for general guidance on matters of interest only. Even if the Company takes every precaution to ensure that the content of the Service is both current and accurate, errors can occur. Plus, given the changing nature of laws, rules and regulations, there may be delays, omissions or inaccuracies in the information contained on the Service.
The Company is not responsible for any errors or omissions, or for the results obtained from the use of this information.

##### Fair Use Disclaimer
The Company may use copyrighted material which has not always been specifically authorized by the copyright owner. The Company is making such material available for criticism, comment, news reporting, teaching, scholarship, or research.
The Company believes this constitutes a "fair use" of any such copyrighted material as provided for in section 107 of the United States Copyright law.
If You wish to use copyrighted material from the Service for your own purposes that go beyond fair use, You must obtain permission from the copyright owner.

##### Views Expressed Disclaimer
The Service may contain views and opinions which are those of the authors and do not necessarily reflect the official policy or position of any other author, agency, organization, employer or company, including the Company.
Comments published by users are their sole responsibility and the users will take full responsibility, liability and blame for any libel or litigation that results from something written in or as a direct result of something written in a comment. The Company is not liable for any comment published by users and reserves the right to delete any comment for any reason whatsoever.

##### No Responsibility Disclaimer
The information on the Service is provided with the understanding that the Company is not herein engaged in rendering legal, accounting, tax, or other professional advice and services. As such, it should not be used as a substitute for consultation with professional accounting, tax, legal or other competent advisers.
In no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever arising out of or in connection with your access or use or inability to access or use the Service.

##### "Use at Your Own Risk" Disclaimer
All information in the Service is provided "as is", with no guarantee of completeness, accuracy, timeliness or of the results obtained from the use of this information, and without warranty of any kind, express or implied, including, but not limited to warranties of performance, merchantability and fitness for a particular purpose.
The Company will not be liable to You or anyone else for any decision made or action taken in reliance on the information given by the Service or for any consequential, special or similar damages, even if advised of the possibility of such damages.

##### Contact Us
If you have any questions about this Disclaimer, you can contact us by email: a.cangi@hzdr.de