---
title: "Research Overview"
meta:
  - name: description
    content: "Official website of the Machine Learning for Materials Design (ML4MD) Lab, led by Attila Cangi. Research overview section."
  - name: keywords
    content: "Machine Learning, Materials Design, AI, Artificial Intelligence, Cangi Lab, Research, Overview, Electronic Structure, Atomistic Simulations, MALA, Molecular Dynamics, Spin Dynamics, Explorative AI"
---

Our lab leverages machine learning and high-performance computing simulations to accelerate the discovery and understanding of new materials. We focus on the following key research thrusts:


## Machine Learning and Electronic Structure Methods

We develop the **Materials Learning Algorithms (MALA)**, a physics-informed machine learning framework designed to accelerate conventional density functional theory simulations. MALA employs neural network architectures to accurately predict electronic structures across different parameter spaces. Our scalable approach overcomes the limitations of conventional density functional theory simulations, paving the way for electronic structure calculations at unprecedented length and time scales.

*   **Key Areas:** Density Functional Theory, Neural Networks, Atomistic Simulations, High-Performance Computing
*   **Related Projects:**
    * [Materials Learning Algorithms (MALA): Scalable Machine Learning for Electronic Structure Calculations in Large-Scale Atomistic Simulations](highlights_content/2509_comp_phys_commun.qmd)
    * [Predicting Electronic Structures at Any Length Scale with Machine Learning](highlights_content/2306_npj_comput_mater.qmd)
    * [Deep Dive into Machine Learning Density Functional Theory for Materials Science and Chemistry](highlights_content/2204_phys_rev_mater.qmd)


## Atomistic Molecular Spin Dynamics

We combine first-principles calculations with machine learning models to generate accurate interatomic potentials for high-performance molecular-spin dynamics simulations. Our computational framework allow simultaneous simulations of ionic and spin dynamics, enabling detailed analyses of structural stability, transport phenomena, and magneto-structural phase transitions. This approach holds promise for developing next-generation magnetic materials and ultrafast magnetic storage technologies.

*   **Key Areas:** Molecular Dynamics, Spin Dynamics, Interatomic Potentials, Magnetic Materials
*   **Related Projects:**
    * [Probing Iron in Earth’s Core with Molecular-Spin Dynamics](highlights_content/2412_iron_pnas.qmd)
    * [Data-Driven Magneto-Elastic Predictions with Scalable Classical Spin-Lattice Dynamics](highlights_content/2109_npj_comput_mater.qmd)


## Explorative Artificial Intelligence for Materials Modeling

We leverage state-of-the-art machine learning techniques to advance and automate first-principles simulations, paving the way for rapid and targeted materials discovery. We employ physics-informed neural networks for inverting fundamental quantum mechanical equations, neural operators for modeling electron dynamics, and generative models for materials discovery.

*   **Key Areas:** Time-Dependent Density Functional Theory, Exchange-Correlation Functionals, Neural Operators, Physics-Informed Neural Networks, AI for Materials Discovery
 