name: Build & Publish Quarto site → GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages:    write        # needed by deploy-pages
  id-token: write        # needed by deploy-pages

env:
  ORCID_ID: ${{ secrets.ORCID_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout
      - uses: actions/checkout@v4

      # 2 Enable Pages (extracts metadata, sets env vars)
      - uses: actions/configure-pages@v4

      # 3 Install Quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # 4 Python deps for BibTeX → YAML
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip bibtexparser pyyaml jq

      # 5 Fetch works from Crossref by ORCID
      - name: Download works JSON via Crossref
        run: |
          curl -fLsS \
            "https://api.crossref.org/works?filter=orcid:${ORCID_ID}&mailto=a.cangi@hzdr.de&rows=1000" \
            -o works.json
          jq '.message.items | length' works.json

      # 6 Convert BibTeX → data/publications.yml
      - name: Convert Crossref JSON to YAML
        run: python scripts/crossref_to_yaml.py

      # 7 Render the Quarto site
      - name: Render site
        run: quarto render

      # 8 Upload the built site as a Pages artifact
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      # 9 Deploy to Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
