name: Quarto Publish – auto-update publications

on:
  push:
    branches: [main]        # rebuild site whenever main changes
  workflow_dispatch:        # …or run it manually from the Actions tab

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    # → Store your ORCID iD as a repository secret named ORCID_ID
    env:
      ORCID_ID: ${{ secrets.ORCID_ID }}

    steps:
      # 1️⃣ check out the repo
      - uses: actions/checkout@v4

      # 2️⃣ set up Quarto CLI
      - uses: quarto-dev/quarto-actions/setup@v2

      # 3️⃣ install Python deps for the conversion script
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip bibtexparser pyyaml

      # 4️⃣ fetch fresh BibTeX from ORCID
      - name: Download BibTeX from ORCID
        run: |
          curl -sSL \
            -H "Accept: application/x-bibtex" \
            "https://pub.orcid.org/v3.0/${ORCID_ID}/works?format=bibtex" \
            -o references.bib
          echo "Fetched $(grep -c @ references.bib) records."

      # 5️⃣ convert BibTeX → YAML for the Quarto listing page
      - name: Convert BibTeX to YAML
        run: python scripts/bib_to_yaml.py

      # 6️⃣ render the site
      - name: Render site
        run: quarto render

      # 7️⃣ publish to GitHub Pages
      - uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
