name: Build & Publish Quarto site → GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages:    write        # needed by deploy-pages
  id-token: write        # needed by deploy-pages

env:
  ORCID_ID: ${{ secrets.ORCID_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout
      - uses: actions/checkout@v4

      # 2 Enable Pages (extracts metadata, sets env vars)
      - uses: actions/configure-pages@v4

      # 3 Install Quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # 4 Python deps for BibTeX → YAML
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip bibtexparser pyyaml

      # 5 Fetch latest works from ORCID (BibTeX)
      - name: Download BibTeX from ORCID
        run: |
          curl -sSL -H "Accept: application/x-bibtex" \
            "https://pub.orcid.org/v3.0/${ORCID_ID}/works?format=bibtex" \
            -o references.bib
          echo "Fetched $(grep -c @ references.bib) records."

      # 6 Convert BibTeX → data/publications.yml
      - name: Convert BibTeX to YAML
        run: python scripts/bib_to_yaml.py

      # 7 Render the Quarto site
      - name: Render site
        run: quarto render

      # 8 Upload the built site as a Pages artifact
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      # 9 Deploy to Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
